apiVersion: apps/v1
kind: Deployment
metadata:
  name: xdp-prometheus
spec:
  selector:
    matchLabels:
      app: xdp-prometheus
  template:
    metadata:
      labels:
        app: xdp-prometheus
    spec:
      containers:
      - name: xdp-prometheus
        image: ghcr.io/srodi/ebpf-prometheus-metrics/xdp-prometheus:157c437
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
        ports:
        - containerPort: 8080
          name: metrics
        securityContext:
          capabilities:
            add:
              - SYS_ADMIN
              - SYS_RESOURCE
---
apiVersion: v1
kind: Service
metadata:
  name: xdp-prometheus
  labels:
    app: xdp-prometheus
spec:
  selector:
    app: xdp-prometheus
  ports:
  - name: metrics
    port: 8080
    targetPort: 8080
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: xdp-prometheus
  labels:
    app: xdp-prometheus
spec:
  selector:
    matchLabels:
      app: xdp-prometheus
  endpoints:
  - port: metrics
    interval: 30s
    path: /metrics
    scheme: http
  namespaceSelector:
    matchNames:
    - default